# src/main/resources/application.yml

spring:
  application:
    name: link-service

  logging:
    level:
      fr.rikiki.rlk: DEBUG
      org.springdoc: DEBUG
      io.swagger.v3: DEBUG
      org.springframework.web: DEBUG
    file:
      name: logs/app.log

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/rikikilink}
    username: ${SPRING_DATASOURCE_USERNAME:rikiki}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}

  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/

server:
  port: 8080   # <-- impératif : correspond au EXPOSE et au mapping Docker 8180:8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: false    # on désactive la génération automatique /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /openapi.yaml  # charge votre fichier static/openapi.yaml