version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: rikikilink-postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rikikilink-net
    labels:
      com.rikikilink.role: database

  redis:
    image: redis:7
    container_name: rikikilink-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - rikikilink-net
    labels:
      com.rikikilink.role: cache

  pgadmin:
    image: dpage/pgadmin4
    container_name: rikikilink-pgadmin
    restart: unless-stopped
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    networks:
      - rikikilink-net
    labels:
      com.rikikilink.role: devtool

  link-service:  
    build:
      context: ../../link-service
    container_name: rikikilink-link-service
    depends_on:
      - postgres
      - redis
    ports:
      - "8180:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_REDIS_HOST: redis
    volumes:
      - ./logs/link-service:/app/logs
    networks:
      - rikikilink-net
    labels:
      com.rikikilink.service: link

  stats-service:
    build:
      context: ../../stat-service
    container_name: rikikilink-stat-service
    depends_on:
      - postgres
      - redis
    ports:
      - "${STATS_SERVICE_PORT:-8082}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_REDIS_HOST: redis
    volumes:
      - ./logs/stats-service:/app/logs
    networks:
      - rikikilink-net
    labels:
      com.rikikilink.service: stat

volumes:
  pgdata:

networks:
  rikikilink-net:
    driver: bridge
